### ISSUE TITLE
Error while parsing schema(s).Location [ file:/usr/eid-applet/eid-applet-service-signer/src/main/resources/ts_102918v010101.xsd{11,98}].

### ISSUE THREAD

**Issue by CodingPeak** [e-Contract/eid-applet#1]
Situation:
I had a normal CentOS webserver with a website in PHP.
I followed the instructions and installed JDK and Maven.
I downloaded the eid-applet repo as zip and uploaded it to my server.
I ran "maven clean install" and it started downloading a whole list of files.

Then i got this exception:
![image](https://cloud.githubusercontent.com/assets/3180443/6898532/1043297a-d6fb-11e4-9db2-a1ec6669f84b.png)

The result: the rest of the installation was skipped.
![image](https://cloud.githubusercontent.com/assets/3180443/6898548/1ffff5b4-d6fb-11e4-8a90-ab78cc40eb18.png)

How should I fix this error?

**Comment by sophiekruijt** [comment]
I had exactly the same error and stil haven't been able to solve this either.

**Comment by CodingPeak** [comment]
Hi stefankruijt,

Thank you for your answer. I'll keep you updated if I find anything usefull.

**Comment by CodingPeak** [comment]
I found this: http://stackoverflow.com/questions/23011547/webservice-client-generation-error-with-jdk8 and this worked for me to install the EId applet!

**Comment by fcorneli** [comment]
I'll check out the eID Applet build process under Java 8.

**Comment by CodingPeak** [comment]
Installation worked.. But building the eid applet failed...

![image](https://cloud.githubusercontent.com/assets/3180443/6943563/22bf1eca-d88f-11e4-83f4-539e3bc7aae3.png)

**Comment by fcorneli** [comment]
Fix for Java 8 compilation: https://github.com/e-Contract/eid-applet/commit/b8cfba66d0462dcbcc3604b42c34dd39009cb0c8

**Comment by fcorneli** [comment]
Closing this one as Java 8 compilation has been fixed.
