### ISSUE TITLE
Update to a newer version of Bouncy Castle

### ISSUE THREAD

**Issue by ncelerier** [e-Contract/eid-applet#6]
Hello, 

Do you have any plan on updating to a newer version of the Bouncy Castle library ?

Regards,
Nicolas.

**Comment by fcorneli** [comment]
The eID Applet Service can already handle BouncyCastle version 1.50 at runtime.

**Comment by ncelerier** [comment]
Thank you for the information. 

However, in the POM, I can see that there is a reference to version 1.45. 
Can you clarify why version 1.50 is not specified instead ?

So if I understand properly, there are currently no plans to update to a newer version.

**Comment by ncelerier** [comment]
I'm asking these questions because we are updating our projects to version 1.52 (jdk15on).

Are you sure that you support 1.50 ? 

When I'm looking at your class AbstractCMSSignatureService, I can see that you use this method : CMSSignedDataGenerator.generate(CMSProcessable content, boolean encapsulate, java.security.Provider sigProvider)

This method is still in 1.49 (http://javadox.com/org.bouncycastle/bcpkix-jdk15on/1.49/org/bouncycastle/cms/CMSSignedDataGenerator.html).

However, it is not in 1.50 anymore (http://javadox.com/org.bouncycastle/bcpkix-jdk15on/1.50/org/bouncycastle/cms/CMSSignedDataGenerator.html).

Am I missing something ?

**Comment by ncelerier** [comment]
Hello fcorneli, 

Did you had the time to have a look at these questions ? 

Thank you.

**Comment by fcorneli** [comment]
We no longer support eid-applet-service-signer in favor of our Digital Signature Service solution.
See also: https://www.e-contract.be/sites/dssp/
